#ifndef __DEFINES_H_
#define __DEFINES_H_

#define NUM_SHIPS	5

enum BSRESULT { BS_FAIL = -1, BS_SUCCESS = 1 };
enum DIRECTION { BS_HORIZ = 0, BS_VERT};
enum SHIPTYPE { BS_CARRIER = 0, BS_BATTLESHIP, BS_CRUISER, BS_SUBMARINE, BS_PATROL };
enum GAMESTATE { WAITING_FOR_INPUT = 0, INPUT_RECEIVED, SHOTS_FIRED, COMPUTERS_TURN, GAME_OVER };
enum BS_SHIP_STATE {SHIP_ALIVE = 0, SHIP_SUNK };

#define SHOT_BOARD_START_X 25
#define SHOT_BOARD_START_Y 4

#define CARRIER	'C'
#define BATTLSHIP 'B'
#define CRUISER	'C'
#define SUBMARINE	'S'
#define PATROL	'P'

#define HIT ','
#define MISS '~'

#endif
